# Домашнее задание №2 по линейной алгебре #

*Выполнила Кулик Екатерина*

In [29]:
import numpy as np

## Задание 1

In [3]:
legislators = ["A", "C", "B", "D", "F", "E", "G", "I", "H", "J"]

bills = [
    ("C", "B"),  
    ("B", "D"),  
    ("F", "E"),  
    ("A", "C"),  
    ("B", "D"),  
    ("H", "J"), 
    ("E", "G"),  
    ("D", "F"),  
    ("G", "I"),  
    ("A", "C")   
]


positions = {legislator: index for index, legislator in enumerate(legislators)}


def get_votes(bill, positions):
    left = positions[bill[0]]
    right = positions[bill[1]]
    votes = []
    for legislator in legislators:
        if positions[legislator] <= left:
            votes.append("Против")
        elif positions[legislator] > right:
            votes.append("За")
        else:
            votes.append("Не голосовал")
    return votes



num_legislators = len(legislators)
num_bills = len(bills)
agreement_matrix = np.zeros((num_legislators, num_legislators))

for bill in bills:
    votes = get_votes(bill, positions)
    for i in range(num_legislators):
        for j in range(num_legislators):
            if votes[i] == votes[j]:
                agreement_matrix[i][j] += 1


agreement_matrix /= num_bills



agreement_matrix

array([[1. , 0.8, 0.7, 0.5, 0.4, 0.3, 0.2, 0.1, 0.1, 0. ],
       [0.8, 1. , 0.7, 0.5, 0.4, 0.3, 0.2, 0.1, 0.1, 0. ],
       [0.7, 0.7, 1. , 0.7, 0.6, 0.5, 0.4, 0.3, 0.3, 0.2],
       [0.5, 0.5, 0.7, 1. , 0.7, 0.6, 0.5, 0.4, 0.4, 0.3],
       [0.4, 0.4, 0.6, 0.7, 1. , 0.8, 0.7, 0.6, 0.6, 0.5],
       [0.3, 0.3, 0.5, 0.6, 0.8, 1. , 0.8, 0.7, 0.7, 0.6],
       [0.2, 0.2, 0.4, 0.5, 0.7, 0.8, 1. , 0.8, 0.8, 0.7],
       [0.1, 0.1, 0.3, 0.4, 0.6, 0.7, 0.8, 1. , 0.9, 0.8],
       [0.1, 0.1, 0.3, 0.4, 0.6, 0.7, 0.8, 0.9, 1. , 0.9],
       [0. , 0. , 0.2, 0.3, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]])

## Задание 2

In [4]:
print("След матрицы:", np.trace(agreement_matrix))

След матрицы: 10.0


In [5]:
print("Определитель матрицы:", np.linalg.det(agreement_matrix))

Определитель матрицы: 5.152319999999997e-05


In [6]:
print("Норма Фробениуса:", np.linalg.norm(agreement_matrix, 'fro'))

Норма Фробениуса: 6.138403701289122


## Задание 3 ##

In [7]:
D2 = (1 - agreement_matrix) ** 2
D2

array([[0.  , 0.04, 0.09, 0.25, 0.36, 0.49, 0.64, 0.81, 0.81, 1.  ],
       [0.04, 0.  , 0.09, 0.25, 0.36, 0.49, 0.64, 0.81, 0.81, 1.  ],
       [0.09, 0.09, 0.  , 0.09, 0.16, 0.25, 0.36, 0.49, 0.49, 0.64],
       [0.25, 0.25, 0.09, 0.  , 0.09, 0.16, 0.25, 0.36, 0.36, 0.49],
       [0.36, 0.36, 0.16, 0.09, 0.  , 0.04, 0.09, 0.16, 0.16, 0.25],
       [0.49, 0.49, 0.25, 0.16, 0.04, 0.  , 0.04, 0.09, 0.09, 0.16],
       [0.64, 0.64, 0.36, 0.25, 0.09, 0.04, 0.  , 0.04, 0.04, 0.09],
       [0.81, 0.81, 0.49, 0.36, 0.16, 0.09, 0.04, 0.  , 0.01, 0.04],
       [0.81, 0.81, 0.49, 0.36, 0.16, 0.09, 0.04, 0.01, 0.  , 0.01],
       [1.  , 1.  , 0.64, 0.49, 0.25, 0.16, 0.09, 0.04, 0.01, 0.  ]])

## Задание 4 ##

In [23]:
mean_row = np.mean(D2, axis=1, keepdims=True)
mean_col = np.mean(D2, axis=0, keepdims=True)
mean_all = np.mean(D2)

C = D2 - mean_row - mean_col + mean_all
C

array([[-0.544, -0.283, -0.405, -0.12 ,  0.064, -0.048,  0.184,  0.284,
         0.384,  0.484],
       [-0.283, -0.202, -0.264, -0.069,  0.035, -0.037,  0.115,  0.175,
         0.235,  0.295],
       [-0.405, -0.264, -0.346, -0.091,  0.053, -0.039,  0.153,  0.233,
         0.313,  0.393],
       [-0.12 , -0.069, -0.091, -0.016,  0.008, -0.024,  0.048,  0.068,
         0.088,  0.108],
       [ 0.064,  0.035,  0.053,  0.008, -0.048, -0.04 , -0.018, -0.018,
        -0.018, -0.018],
       [-0.048, -0.037, -0.039, -0.024, -0.04 , -0.052,  0.03 ,  0.05 ,
         0.07 ,  0.09 ],
       [ 0.184,  0.115,  0.153,  0.048, -0.018,  0.03 , -0.068, -0.108,
        -0.148, -0.188],
       [ 0.284,  0.175,  0.233,  0.068, -0.018,  0.05 , -0.108, -0.168,
        -0.228, -0.288],
       [ 0.384,  0.235,  0.313,  0.088, -0.018,  0.07 , -0.148, -0.228,
        -0.308, -0.388],
       [ 0.484,  0.295,  0.393,  0.108, -0.018,  0.09 , -0.188, -0.288,
        -0.388, -0.488]])

## Задание 5

In [24]:
Y = -0.5 * C
Y

array([[ 0.272 ,  0.1415,  0.2025,  0.06  , -0.032 ,  0.024 , -0.092 ,
        -0.142 , -0.192 , -0.242 ],
       [ 0.1415,  0.101 ,  0.132 ,  0.0345, -0.0175,  0.0185, -0.0575,
        -0.0875, -0.1175, -0.1475],
       [ 0.2025,  0.132 ,  0.173 ,  0.0455, -0.0265,  0.0195, -0.0765,
        -0.1165, -0.1565, -0.1965],
       [ 0.06  ,  0.0345,  0.0455,  0.008 , -0.004 ,  0.012 , -0.024 ,
        -0.034 , -0.044 , -0.054 ],
       [-0.032 , -0.0175, -0.0265, -0.004 ,  0.024 ,  0.02  ,  0.009 ,
         0.009 ,  0.009 ,  0.009 ],
       [ 0.024 ,  0.0185,  0.0195,  0.012 ,  0.02  ,  0.026 , -0.015 ,
        -0.025 , -0.035 , -0.045 ],
       [-0.092 , -0.0575, -0.0765, -0.024 ,  0.009 , -0.015 ,  0.034 ,
         0.054 ,  0.074 ,  0.094 ],
       [-0.142 , -0.0875, -0.1165, -0.034 ,  0.009 , -0.025 ,  0.054 ,
         0.084 ,  0.114 ,  0.144 ],
       [-0.192 , -0.1175, -0.1565, -0.044 ,  0.009 , -0.035 ,  0.074 ,
         0.114 ,  0.154 ,  0.194 ],
       [-0.242 , -0.1475, -0.1965, -0

In [26]:
eigenvalues, eigenvectors = np.linalg.eig(Y)
max_eigenvalue_index = np.argmax(eigenvalues)
first_eigenvector = eigenvectors[:, max_eigenvalue_index]

print(f"Первый собственный вектор:{first_eigenvector}")

Первый собственный вектор:[ 0.49258373  0.29688638  0.39999353  0.11194396 -0.04182487  0.06930789
 -0.18425695 -0.28290075 -0.38154456 -0.48018836]


In [28]:
legislator_positions = list(zip(legislators, first_eigenvector))


sorted_legislators = sorted(legislator_positions, key=lambda x: x[1])

true_order = ['A', 'C', 'B', 'D', 'F', 'E', 'G', 'I', 'H', 'J']
true_order_reversed = true_order[::-1]


print("\nИстинное упорядочение:")
print(" - ".join(true_order_reversed))


sorted_legislators_only = [legislator for legislator, position in sorted_legislators]
print("\nУпорядочение по собственному вектору:")
print(" - ".join(sorted_legislators_only))


Истинное упорядочение:
J - H - I - G - E - F - D - B - C - A

Упорядочение по собственному вектору:
J - I - H - G - E - F - D - B - C - A


**Вывод:**

Упорядочение, полученное по первому собственному вектору, приблизительно соответствует истинному упорядочению законодателей. Это подтверждает, что метод нахождения первого собственного вектора успешно восстанавливает истинное взаимное расположение законодателей на политической шкале.